### ISSUE TITLE
ImportError: ~\Anaconda3\lib\site-packages\pymlink-1.3.0-py3.7.egg\py_mlink/MLink32 not found.

### ISSUE THREAD

**Issue by galatealab** [microdaq/PyMLink#7]
Trying to run the demo files, I get an error when loading the library. 
Installation was done as instructed in the readme without error.

`from py_mlink import PyMLink`

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\Anaconda3\lib\site-packages\pymlink-1.3.0-py3.7.egg\py_mlink\ctypes_mlink.py in load_library(self, libname)
    528         try:
--> 529             result = LibraryLoader.load_library(self, libname)
    530         except ImportError:

~\Anaconda3\lib\site-packages\pymlink-1.3.0-py3.7.egg\py_mlink\ctypes_mlink.py in load_library(self, libname)
    363 
--> 364         raise ImportError("%s not found." % libname)
    365 

ImportError:~\Anaconda3\lib\site-packages\pymlink-1.3.0-py3.7.egg\py_mlink/MLink32 not found.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
 in 
      3 # Embedded-solutions, November 2017-2019
      4 
----> 5 from py_mlink import PyMLink
      6 
      7 # Create MLink object, connect to MicroDAQ device

~\Anaconda3\lib\site-packages\pymlink-1.3.0-py3.7.egg\py_mlink\PyMLink.py in 
      5 import ctypes
      6 from functools import wraps
----> 7 from py_mlink import ctypes_mlink as cml
      8 
      9 

~\Anaconda3\lib\site-packages\pymlink-1.3.0-py3.7.egg\py_mlink\ctypes_mlink.py in 
    598 
    599 libname_ver = libpath+libname_ver
--> 600 _libs["MLink"] = load_library(libname_ver)
    601 
    602 

~\Anaconda3\lib\site-packages\pymlink-1.3.0-py3.7.egg\py_mlink\ctypes_mlink.py in load_library(self, libname)
    544                     result = None
    545             if result is None:
--> 546                 raise ImportError("%s not found." % libname)
    547         return result
    548 

ImportError: ~\Anaconda3\lib\site-packages\pymlink-1.3.0-py3.7.egg\py_mlink/MLink32 not found.

**Comment by witczenko** [comment]
Hi @galatealab,
based on provided traceback I deduce you're using python 3.7 with the Anaconda package manager. Am I right? 
Could you provide details about used operating system?

Regards, 
@witczenko

**Comment by galatealab** [comment]
Hi.

I checked again today but with a different environment (anaconda3->spyder4 & jupyter notebook)and it seems to work fine. I can run the demo code with them.

My issue occurred with visual studio code in the following configuration:

-        Anaconda3 for the python kernel

-        Visual studio code for the code environment

o   Using the anaconda3 kernel from within VSC.

-        Daq was not connected to PC

I reinstalled VSC to have a clean start and connected the daq by wifi and this time it worked also with VSC.

Issue closed.

My apologize for the unnecessary notification.

Samuel

**Comment by witczenko** [comment]
Hi, 
I am glad to hear you make it through, nonetheless I am curious what happened. I'll take into account your setup (VSC + anaconda3) when releasing new packages in order to check compatibility. Maybe there is a gap in installation script. 

@galatealab thanks for feedback!

Regards, 
@witczenko
